package it.polimi.ingsw.psp58.event.gameEvents;

import it.polimi.ingsw.psp58.event.core.ControllerListener;
import it.polimi.ingsw.psp58.event.core.ViewListener;

import java.io.Serializable;

/**
 * @author Alessandro Lisi
 * a generic GameEvent generated by an EventManager to notify an EventListener
 */
public abstract class GameEvent implements Serializable {
    private final String description;

    public GameEvent( String description) {
        this.description = description;
    }


    //public abstract  EventType getEventType();
    public String getEventDescription() {
        return this.description;
    }


    public void notifyHandler(ViewListener viewListener){
    }

    public void notifyHandler(ControllerListener controllerListener){
    }
}