package it.polimi.ingsw.psp58.event.gameEvents;

import it.polimi.ingsw.psp58.event.core.ControllerListener;
import it.polimi.ingsw.psp58.event.core.ViewListener;

import java.io.Serializable;

/**
 * @author Alessandro Lisi
 * A generic GameEvent generated by an EventManager to notify an EventListener
 */
public abstract class GameEvent implements Serializable {
    private final String description;

    public GameEvent( String description) {
        this.description = description;
    }

    public String getEventDescription() {
        return this.description;
    }


    /**
     * Method used to the event to notify a class that implements a {@link ControllerListener} interface calling his {@code handleEvent}
     * @param viewListener the listener to notify
     */
    public void notifyHandler(ViewListener viewListener){
    }

    /**
     * Method used to the event to notify a class that implements a {@link ViewListener} interface calling his {@code handleEvent}
     * @param controllerListener the listener to notify
     */
    public void notifyHandler(ControllerListener controllerListener){
    }
}