package event.events;

/**
 * @author Alessandro Lisi
 * a generic GameEvent generated by an EventManager to notify an EventListener
 */
public abstract class GameEvent {

    private final String description;

    public GameEvent(String description) {
        this.description = description;
    }


    //public abstract  EventType getEventType();
    public String getEventDescription() {
        return this.description;
    }

}