package event.gameEvents;

import event.core.EventListener;

import java.io.Serializable;

/**
 * @author Alessandro Lisi
 * a generic GameEvent generated by an EventManager to notify an EventListener
 */
public abstract class GameEvent implements Serializable {
    private final String description;

    public GameEvent( String description) {
        this.description = description;
    }


    //public abstract  EventType getEventType();
    public String getEventDescription() {
        return this.description;
    }

    public abstract void notifyHandler(EventListener listener);

}